tap:
  docker:
    registry: docker.io/kubeshark
    tag: ""
    tagLocked: true
    imagePullPolicy: Always
    imagePullSecrets: []
    overrideTag:
      worker: ""
      hub: ""
      front: ""
  proxy:
    worker:
      srvPort: 30001
    hub:
      srvPort: 8898
    front:
      port: 8899
    host: 127.0.0.1
  regex: .*
  namespaces: []
  excludedNamespaces: []
  bpfOverride: ""
  stopped: true
  release:
    repo: https://helm.kubeshark.co
    name: kubeshark
    namespace: default
  persistentStorage: false
  persistentStorageStatic: false
  efsFileSytemIdAndPath: ""
  storageLimit: 5000Mi
  storageClass: standard
  dryRun: false
  resources:
    hub:
      limits:
        cpu: 1000m
        memory: 1500Mi
      requests:
        cpu: 50m
        memory: 50Mi
    sniffer:
      limits:
        cpu: 1000m
        memory: 1500Mi
      requests:
        cpu: 50m
        memory: 50Mi
    tracer:
      limits:
        cpu: 1000m
        memory: 1500Mi
      requests:
        cpu: 50m
        memory: 50Mi
  serviceMesh: true
  tls: true
  disableTlsLog: false
  packetCapture: best
  ignoreTainted: false
  labels: {}
  annotations: {}
  nodeSelectorTerms:
  - matchExpressions:
    - key: kubernetes.io/os
      operator: In
      values:
      - linux
  auth:
    enabled: false
    type: saml
    saml:
      idpMetadataUrl: ""
      x509crt: ""
      x509key: ""
      roleAttribute: role
      roles:
        admin:
          filter: ""
          canDownloadPCAP: true
          canUseScripting: true
          canUpdateTargetedPods: true
          canStopTrafficCapturing: true
          showAdminConsoleLink: true
  ingress:
    enabled: false
    className: ""
    host: ks.svc.cluster.local
    tls: []
    annotations: {}
  ipv6: true
  debug: false
  kernelModule:
    enabled: false
    image: kubeshark/pf-ring-module:all
    unloadOnDestroy: false
  telemetry:
    enabled: true
  sentry:
    enabled: false
    environment: production
  defaultFilter: "!dns and !tcp"
  scriptingDisabled: false
  targetedPodsUpdateDisabled: false
  recordingDisabled: false
  stopTrafficCapturingDisabled: false
  capabilities:
    networkCapture:
    - NET_RAW
    - NET_ADMIN
    serviceMeshCapture:
    - SYS_ADMIN
    - SYS_PTRACE
    - DAC_OVERRIDE
    kernelModule:
    - SYS_MODULE
    ebpfCapture:
    - SYS_ADMIN
    - SYS_PTRACE
    - SYS_RESOURCE
    - IPC_LOCK
  globalFilter: ""
  enabledDissectors:
  - amqp
  - dns
  - http
  - icmp
  - kafka
  - redis
  - sctp
  - syscall
  - tcp
  - ws
  metrics:
    port: 49100
  pprof:
    enabled: false
    port: 8000
    view: flamegraph
  misc:
    jsonTTL: 5m
    pcapTTL: 10s
    pcapErrorTTL: 60s
    trafficSampleRate: 100
    tcpStreamChannelTimeoutMs: 10000
    tcpStreamChannelTimeoutShow: false
    resolutionStrategy: auto
    duplicateTimeframe: 200ms
    detectDuplicates: false
logs:
  file: ""
  grep: ""
kube:
  configPath: ""
  context: ""
dumpLogs: false
headless: false
license: ""
cloudLicenseEnabled: true
supportChatEnabled: true
internetConnectivity: true
dissectorsUpdatingEnabled: true
scripting:
  env: {}
  source: ""
  watchScripts: true
timezone: ""
