apiVersion: v1
kind: Service
metadata:
  name: { { .Values.service.name } }
  namespace: { { .Release.Namespace } }
spec:
  type: { { .Values.service.type } }
  ports:
    - name: api
      port: { { .Values.service.port } }
      targetPort: { { .Values.pod.port } }
      protocol: TCP
  selector:
    app: { { .Values.pod.name } }
