---
{{- if .Values.tap.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  creationTimestamp: null
  labels:
    kubeshark-cli-version: v1
    kubeshark-created-by: kubeshark
    kubeshark-managed-by: kubeshark
  name: kubeshark-ingress-class
  namespace: '{{ .Values.tap.selfnamespace }}'
spec:
  controller: k8s.io/ingress-nginx
{{- end }}
