---
{{- if .Values.tap.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: {{ .Values.tap.ingress.certmanager }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  {{- if .Values.tap.annotations }}
    {{- toYaml .Values.tap.annotations | nindent 4 }}
  {{- end }}
  creationTimestamp: null
  labels:
  {{- if .Values.tap.labels }}
    {{- toYaml .Values.tap.labels | nindent 4 }}
  {{- end }}
  name: kubeshark-ingress
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: {{ .Values.tap.ingress.classname }}
  rules:
    - host: {{ .Values.tap.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: kubeshark-hub
                port:
                  number: 80
            path: /api(/|$)(.*)
            pathType: Prefix
          - backend:
              service:
                name: kubeshark-front
                port:
                  number: 80
            path: /()(.*)
            pathType: Prefix
  tls:
  {{- if gt (len .Values.tap.ingress.tls) 0}}
    {{- toYaml .Values.tap.ingress.tls | nindent 2 }}
  {{- end }}
status:
  loadBalancer: {}
{{- end }}
