name: acceptance tests

on:
  pull_request:
    branches:
      - 'main'
      - 'develop'
  push:
    branches:
      - 'develop'

concurrency:
  group: mizu-acceptance-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-acceptance-tests:
    name: Run acceptance tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Setup acceptance test
        run: source ./acceptanceTests/setup.sh

      - name: Test
        run: make acceptance-test
