on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Build

concurrency:
  group: kubeshark-pr-validation-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-cli:
    name: CLI executable build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Check modified files
        id: modified_files
        run: devops/check_modified_files.sh cli/

      - name: Set up Go 1.17
        if: steps.modified_files.outputs.matched == 'true'
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Build CLI
        if: steps.modified_files.outputs.matched == 'true'
        run: make cli

  build-agent:
    name: Agent docker image build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Check modified files
        id: modified_files
        run: devops/check_modified_files.sh agent/ shared/ tap/ ui/ Dockerfile

      - name: Set up Docker Buildx
        if: steps.modified_files.outputs.matched == 'true'
        uses: docker/setup-buildx-action@v1

      - name: Build
        uses: docker/build-push-action@v2
        if: steps.modified_files.outputs.matched == 'true'
        with:
          context: .
          push: false
          tags: kubeshark/kubeshark:devlatest
          cache-from: type=gha
          cache-to: type=gha,mode=max
