name: Static code analysis

on:
  pull_request:
    branches:
      - 'develop'
      - 'main'
  push:
    branches:
      - 'develop'
      - 'main'

permissions:
  contents: read

jobs:
  golangci:
    name: Go lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libpcap-dev

      - name: Go lint - agent
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: agent
          args: --timeout=5m

      - name: Go lint - shared
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: shared
          args: --timeout=5m

      - name: Go lint - tap
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: tap
          args: --timeout=5m

      - name: Go lint - CLI
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: cli
          args: --timeout=5m
